config/routes.rb
Rails.application.routes.draw do
  
  resources :maquinas
  resources :clientes

  get 'wellcome/index'

  

  root 'wellcome#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_many :maquinas
  validates :nombre, presence: true
  validates :cuit, presence: true,
                   length: { is: 11 }
  validates :direccion, presence: true
  validates :telefono, presence: true
end

app/models/maquina.rb
class Maquina < ActiveRecord::Base
  belongs_to :cliente
  validates :num_serie, presence: true
  validates :contador, presence: true
  validates :estado, presence: true
end

app/models/modelo.rb
class Modelo < ActiveRecord::Base

 has_many: :maquinas
 has_many: :partes
end

app/models/parte.rb
class Parte < ActiveRecord::Base
  belongs_to: :modelo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController

  def index
    @clientes = Cliente.all
  end

  def new
    @cliente = Cliente.new
  end

  def edit
    @cliente = Cliente.find(params[:id])
  end

  def update
    @cliente = Cliente.find(params[:id])
 
    if @cliente.update(cliente_parametros)
      redirect_to @cliente
    else
      render 'edit'
    end
  end

  def create
    @cliente = Cliente.new(cliente_parametros)
	if @cliente.save
	  redirect_to '/clientes'
	else
	  render 'new'
        end
  end

  def show 
    @cliente = Cliente.find(params[:id]) 
    @maquinas = @cliente.maquinas
  end

  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy
 
    redirect_to clientes_path
  end

  private
    def cliente_parametros
    
      params.require(:cliente).permit(:nombre, :cuit, :direccion, :localidad, :provincia, :codigo_postal, :limite_credito, :telefono, :celular, :email) 
    
    end

end

app/controllers/maquinas_controller.rb
class MaquinasController < ApplicationController
  def index
    @maquinas = Maquina.all
  end

  def new
    @maquina = Maquina.new  
  end

  def edit
    @maquina = Maquina.find(params[:id])
  end

  def create
    @maquina = Maquina.new(maquina_params)
 
    if @maquina.save
      redirect_to @maquina
    else
      render 'new'
    end
  end

  def update
    @maquina = Maquina.find(params[:id])
 
    if @maquina.update(maquina_params)
      redirect_to @maquina
    else
      render 'edit'
    end
  end

  def show
    @maquina = Maquina.find(params[:id])
  end
 
  def destroy
    @maquina = Maquina.find(params[:id])
    @maquina.destroy
 
    redirect_to maquinas_path
  end

  private
  def maquina_params
    params.require(:maquina).permit(:num_serie, :contador,:estado)
  end
 
end

app/controllers/wellcome_controller.rb
class WellcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/maquinas_helper.rb
module MaquinasHelper
end

app/helpers/wellcome_helper.rb
module WellcomeHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@cliente.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @cliente.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <p>
    <%= f.label :nombre %><br>
    <%= f.text_field(:nombre) %>
    </p>

    <p>
    <%= f.label :cuit %><br>
    <%= f.text_field(:cuit) %>
    </p>

    <p>
    <%= f.label :direccion %><br>
    <%= f.text_field(:direccion) %>
    </p>

    <p>
    <%= f.label :localidad %><br>
    <%= f.text_field(:localidad) %>
    </p>

    <p>
    <%= f.label :provincia %><br>
    <%= f.text_field(:provincia) %>
    </p>

    <p>
    <%= f.label :codigo_postal %><br>
    <%= f.text_field(:codigo_postal) %>
    </p>
    
    <p>
    <%= f.label :limite_credito %><br>
    <%= f.number_field(:limite_credito) %>
    </p>

    <p>
    <%= f.label :telefono %><br>
    <%= f.telephone_field(:telefono) %>
    </p>

    <p>
    <%= f.label :celular %><br>
    <%= f.telephone_field(:celular) %>
    </p>

    <p>
    <%= f.label :email %><br>
    <%= f.email_field(:email) %>
    </p>

  </div>
  <div>
    <%= f.submit "Guardar" %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>
<%= render 'form' %>

app/views/clientes/index.html.erb
<h1>Clientes</h1>
	
<% @clientes.each do |cliente| %>
<div>
  <p>Nombre: <%= cliente.nombre %></p>
  <p><%= link_to "Detalles", cliente_path(cliente) %>
     <%= link_to 'Editar', edit_cliente_path(cliente) %>
     <%= link_to 'Borrar', cliente_path(cliente), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  <p></p>
</div>
<% end %>

<%= link_to 'Nuevo Cliente', "clientes/new" %>

app/views/clientes/new.html.erb
<h1>Nuevo Cliente</h1>
<%= render 'form' %>

app/views/clientes/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>


<h2><%= @cliente.nombre %></h2>
<p>cliente.cuit <%= @cliente.cuit %></p>
<p>cliente.direccion <%= @cliente.direccion %></p>
<p>cliente.localidad <%= @cliente.localidad %></p>
<p>cliente.provincia <%= @cliente.provincia %></p>
<p>cliente.codigo_postal <%= @cliente.codigo_postal %></p>
<p>cliente.limite_credito <%= @cliente.limite_credito %></p>
<p>cliente.telefono <%= @cliente.telefono %></p>
<p>cliente.celular <%= @cliente.celular %></p>
<p>cliente.email <%= @cliente.email %></p>

   <% @maquinas.each do |m| %>
      <div class="card col-xs-4">
	<p>numeroserie: <%= m.num_serie %></p>
	<%= link_to "Detalles", maquina_path(m) %>
      </div>
   <% end %>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sra</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/maquinas/_form.html.erb
<%= form_for :maquina, url: maquinas_path do |f| %>

  <% if @maquina.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@maquina.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @maquina.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :num_serie %><br>
    <%= f.text_field :num_serie %>
  </p>

  <p>
    <%= f.label :contador %><br>
    <%= f.number_field :contador %>
  </p>

  <p>

<%= f.radio_button 'estado', '0' %><%= f.label :estado ,'Stock' %><br />
<%= f.radio_button 'estado', '1' %><%= f.label :estado ,'Alquilada' %><br />
<%= f.radio_button 'estado', '2' %><%= f.label :estado ,'Vendida' %><br />
<%= f.radio_button 'estado', '3' %><%= f.label :estado ,'Scrap' %><br />
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/maquinas/_formulario.html.erb
<%= form_for :maquina do |f| %>

  <% if @maquina.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@maquina.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @maquina.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :num_serie %><br>
    <%= f.text_field :num_serie %>
  </p>

  <p>
    <%= f.label :contador %><br>
    <%= f.number_field :contador %>
  </p>

  <p>

<%= f.radio_button 'estado', '0' %><%= f.label :estado ,'Stock' %><br />
<%= f.radio_button 'estado', '1' %><%= f.label :estado ,'Alquilada' %><br />
<%= f.radio_button 'estado', '2' %><%= f.label :estado ,'Vendida' %><br />
<%= f.radio_button 'estado', '3' %><%= f.label :estado ,'Scrap' %><br />
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/maquinas/edit.html.erb
<h1>Editar Maquina</h1>

<%= render 'form' %> 

<%= link_to 'Back', maquinas_path %>

app/views/maquinas/index.html.erb
<h1>maquinas</h1>
<% @maquinas.each do |maquina| %>
<div>
  <p>num_serie: <%= maquina.num_serie %></p>
  <%= link_to "Detalles", maquina_path(maquina) %>
  <%= link_to "Editar", edit_maquina_url(maquina) %>
  <%= link_to 'Borrar', maquina_path(maquina), method: :delete, data: { confirm: '¿Está seguro?' } %>
  <p></p>
</div>
<% end %>

<%= link_to 'Nueva Maquina', "maquinas/new" %>

app/views/maquinas/new.html.erb
<h1>Nueva maquina</h1>

<%= render 'form' %>

<%= link_to 'Back', maquinas_path %>

app/views/maquinas/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

        <p>num. serie: <%= @maquina.num_serie %></p>
        <p>contador: <%= @maquina.contador %></p>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

app/views/wellcome/index.html.erb
<h1>SRA v0.1 desa</h1>
<%= link_to 'Clientes', "/clientes" %>
<%= link_to 'Maquinas', "/maquinas" %>